"""actualizacion base de datos para reservas

Revision ID: 08be49eb7a3a
Revises: 
Create Date: 2024-03-18 13:21:32.805671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08be49eb7a3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserva', sa.String(length=255), nullable=True))
        batch_op.drop_column('fecha_reserva')
        batch_op.drop_column('hora_reserva')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_reserva', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_reserva', sa.DATE(), nullable=True))
        batch_op.drop_column('reserva')

    # ### end Alembic commands ###
