"""Actualizar modelo de Estudiante: añadir tablas votación profesores4

Revision ID: 10da57430766
Revises: 40b9eedee203
Create Date: 2024-05-13 12:53:36.421388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10da57430766'
down_revision = '40b9eedee203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.create_unique_constraint('nombre_unico', ['nombre'])
    # ### end Alembic commands ###
