"""Actualizar modelo de Estudiante: actualizando tabla foto y relaciones2

Revision ID: 12d18d2435a8
Revises: 451f503d88a2
Create Date: 2024-05-03 22:27:48.130889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d18d2435a8'
down_revision = '451f503d88a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('estudiante_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.alter_column('estudiante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
