"""Actualizar modelo de Estudiante: actualizando tabla foto y relaciones9

Revision ID: 1fbb92dcc59d
Revises: 12d18d2435a8
Create Date: 2024-05-04 14:05:56.473807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbb92dcc59d'
down_revision = '12d18d2435a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.drop_column('especialidad')

    # ### end Alembic commands ###
