"""elimininando tabla fotos

Revision ID: 23943f2157b8
Revises: 1a957758c387
Create Date: 2024-04-04 15:42:39.002716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23943f2157b8'
down_revision = '1a957758c387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('estudiante_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('archivo', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
