"""Actualizar modelo de Estudiante: añadir tablas votación profesores2

Revision ID: 40b9eedee203
Revises: 4a6342d1c25f
Create Date: 2024-05-13 11:53:51.905505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b9eedee203'
down_revision = '4a6342d1c25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.drop_column('especialidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
