"""creando tabla reserva4

Revision ID: 41e9ae714635
Revises: 8898dbca41fb
Create Date: 2024-03-30 20:56:23.660502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e9ae714635'
down_revision = '8898dbca41fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estudiante_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_reserva_estudiante', 'estudiante', ['estudiante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reserva_estudiante', type_='foreignkey')
        batch_op.drop_column('estudiante_id')

    # ### end Alembic commands ###
