"""Actualizar modelo de Estudiante: eliminar password y añadir correo

Revision ID: 4bb09b9c6134
Revises: 23943f2157b8
Create Date: 2024-04-15 13:54:07.286471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb09b9c6134'
down_revision = '23943f2157b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.String(length=100), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('correo')

    # ### end Alembic commands ###
