"""Actualizar modelo de Estudiante: añadir tablas votación profesores6

Revision ID: 59acf0816a5c
Revises: 91acd8b46192
Create Date: 2024-05-13 14:12:02.845752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59acf0816a5c'
down_revision = '91acd8b46192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voto', schema=None) as batch_op:
        batch_op.drop_column('voto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voto', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
