"""añadiendo campos de pago y pack

Revision ID: 75da18daca78
Revises: 62a22761583a
Create Date: 2024-04-04 13:31:40.410884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75da18daca78'
down_revision = '62a22761583a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('pack', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_column('pack')
        batch_op.drop_column('pagado')

    # ### end Alembic commands ###
