"""Actualizar modelo de Estudiante: eliminar dni

Revision ID: 7dcbd22c0332
Revises: 4bb09b9c6134
Create Date: 2024-05-02 12:52:35.501688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcbd22c0332'
down_revision = '4bb09b9c6134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_column('dni')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
