"""creando tabla reserva3

Revision ID: 8898dbca41fb
Revises: 4dcbe3b46ce3
Create Date: 2024-03-30 20:54:07.447166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8898dbca41fb'
down_revision = '4dcbe3b46ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_column('reserva')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserva', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
