"""Actualizar modelo de Estudiante: añadir tablas votación profesores5

Revision ID: 91acd8b46192
Revises: 10da57430766
Create Date: 2024-05-13 13:51:52.200352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91acd8b46192'
down_revision = '10da57430766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estudiantes_profesores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiantes_profesores',
    sa.Column('estudiante_id', sa.INTEGER(), nullable=False),
    sa.Column('profesor_id', sa.INTEGER(), nullable=False),
    sa.Column('voto', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('estudiante_id', 'profesor_id')
    )
    # ### end Alembic commands ###
