"""Actualizar modelo de Estudiante: añadir segundo apellido

Revision ID: abf33e5979ec
Revises: 7dcbd22c0332
Create Date: 2024-05-02 12:53:50.244155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf33e5979ec'
down_revision = '7dcbd22c0332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('apellido2', sa.String(length=100), nullable=True))
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('apellido2')
        batch_op.drop_column('apellido1')

    # ### end Alembic commands ###
